--pwd:user1
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('user1', '$2a$10$euZUL0x9P4OVepyftqNuWe4WVlvNx6yAPMlNZxKdMvt9hlZvEDag.', 1);
--pwd: admin
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('admin', '$2a$10$5dwa94.QckINk/ZdgQTXT.2jriHDqyHsGDu03eQYZ4UnYBAg8.jam', 1);

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('user2', '$2a$10$aOinG/iVThcBeQwaFBri0.SCiMpA8.MJG5r/hoEVGa/uJRZkC1MgK', 1);

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('user1', 'USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('user2', 'USER');

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('admin', 'USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('admin', 'ADMIN');

